// code generated by "stringer -type Repeat"; DO NOT EDIT.

package xtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Never-0]
	_ = x[Daily-1]
	_ = x[Weekly-2]
	_ = x[Monthly-3]
	_ = x[Yearly-4]
}

const _Repeat_name = "NeverDailyWeeklyMonthlyYearly"

var _Repeat_index = [...]uint8{0, 5, 10, 16, 23, 29}

func (i Repeat) String() string {
	if i < 0 || i >= Repeat(len(_Repeat_index)-1) {
		return "Repeat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Repeat_name[_Repeat_index[i]:_Repeat_index[i+1]]
}
